# This Makefile is only for testing. C callers should follow the instructions
# in ./README.md to incorporate these C files into their existing build.

PROGS = blake3 blake3-asm example
CC=gcc
CFLAGS=-O3 -Wall -Wextra -std=c11 -pedantic -fstack-protector-strong -D_FORTIFY_SOURCE=2 -fPIE -fvisibility=hidden
LDFLAGS=-pie -Wl,-z,relro,-z,now
TARGETS=
ASM_TARGETS=
EXTRAFLAGS=-Wa,--noexecstack

ifdef BLAKE3_NO_SSE2
EXTRAFLAGS += -DBLAKE3_NO_SSE2
else
TARGETS += blake3_sse2.o
ASM_TARGETS += blake3_sse2_x86-64_unix.o
endif

ifdef BLAKE3_NO_SSE41
EXTRAFLAGS += -DBLAKE3_NO_SSE41
else
TARGETS += blake3_sse41.o
ASM_TARGETS += blake3_sse41_x86-64_unix.o
endif

ifdef BLAKE3_NO_AVX2
EXTRAFLAGS += -DBLAKE3_NO_AVX2
else
TARGETS += blake3_avx2.o
ASM_TARGETS += blake3_avx2_x86-64_unix.o
endif

ifdef BLAKE3_NO_AVX512
EXTRAFLAGS += -DBLAKE3_NO_AVX512
else
TARGETS += blake3_avx512.o
ASM_TARGETS += blake3_avx512_x86-64_unix.o
endif

ifdef BLAKE3_USE_NEON
EXTRAFLAGS += -DBLAKE3_USE_NEON=1
TARGETS += blake3_neon.o
endif

ifdef BLAKE3_NO_NEON
EXTRAFLAGS += -DBLAKE3_USE_NEON=0
endif

all: blake3
asm: blake3-asm

common-objs = blake3.o blake3_dispatch.o blake3_portable.o

blake3-objs = main.o $(common-objs) $(TARGETS)
blake3: $(blake3-objs)

blake3-asm-objs = main.o $(common-objs) $(ASM_TARGETS)
blake3-asm: $(blake3-asm-objs)

example-objs = example.o $(common-objs) $(ASM_TARGETS)
example: $(example-objs)

$(PROGS):
	$(CC) $(CFLAGS) $(EXTRAFLAGS) -o $@ $($@-objs) $(LDFLAGS)

.c.o:
	$(CC) $(CFLAGS) $(EXTRAFLAGS) $($@_CFLAGS) -o $@ -c $<

.S.o:
	$(CC) $(CFLAGS) $(EXTRAFLAGS) -o $@ -c $<

blake3_sse2.o_CFLAGS = -msse2
blake3_sse41.o_CFLAGS = -msse4.1
blake3_avx2.o_CFLAGS = -mavx2
blake3_avx512.o_CFLAGS = -mavx512f -mavx512vl

test: CFLAGS += -DBLAKE3_TESTING -fsanitize=address,undefined
test: blake3
	./test.py blake3

test_asm: CFLAGS += -DBLAKE3_TESTING -fsanitize=address,undefined
test_asm: blake3-asm
	./test.py blake3-asm

clean:
	rm -f $(PROGS) *.o

.PHONY: clean all asm test test_asm
